### ISSUE TITLE
browser.runtime is not implemented

### ISSUE THREAD

**Issue by kartikwatwani** [Lusito/mockzilla#9]
I am using `browser.runtime` in my code then in the test file I am using mockzilla as follows:
```
 */
 import type { Browser } from "webextension-polyfill-ts";
 import { deepMock } from "mockzilla";
 const [browser, mockBrowser, mockBrowserNode] = deepMock<Browser>("browser",false);
 jest.mock("webextension-polyfill-ts", () => ({ browser }));
```
But when I am running tests I am getting the following error:
```
Test suite failed to run

    Mock "browser.runtime" is not implemented

    Invocation: 
```

What should I do to run my tests if I use `browser.runtime`. If I wish to implement `browser.runtime` myself can you guide me on it?

Update: I also tried `browser.tabs` but that is also not working.

**Comment by Lusito** [comment]
Before every use of a browser property during tests, you'll need to mock it (for example using the expect syntax). See https://lusito.github.io/mockzilla-webextension/browser.html#solution

**Comment by kartikwatwani** [comment]
I learned how to use this module. Thanks for this!
